import { HeroCatalogSchema, type HeroCatalog } from "./schema";

/**
 * Notes:
 * - Skills are definition-only: names + type + optional slot.
 * - Trait effects are stored structurally (hp/atk/def %) for later compute.
 * - Roles are best-effort based on skill names; tweak anytime.
 */

const CATALOG: HeroCatalog = {
  version: "2026-01-10",

  traits: [
    {
      id: "trait_super_sensing",
      name: "Super Sensing",
      effect: {
        stats: { hpPct: 0.20, atkPct: 0.20, defPct: 0.20 },
        summary: "Flat +20% HP/ATK/DEF. Inherent to UR heroes (per your notes).",
      },
    },
    {
      id: "trait_special_tactics",
      name: "Special Tactics",
      effect: {
        stats: { hpPct: 0.10, atkPct: 0.10, defPct: 0.10 },
        summary: "Flat +10% HP/ATK/DEF. Inherent to SSR heroes (per your notes).",
      },
    },
    {
      id: "trait_field_combat",
      name: "Field Combat",
      effect: {
        stats: { hpPct: 0.05, atkPct: 0.05, defPct: 0.05 },
        summary: "Flat +5% HP/ATK/DEF. Inherent to SR heroes (per your notes).",
      },
    },
  ],

  heroes: [
    // ----------------
    // UR — TANK
    // ----------------
    {
      id: "kimberly",
      name: "Kimberly",
      rarity: "UR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: ["buffer"],
      damageProfile: "mixed",
      utilityTags: ["energy", "burst"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "kimberly_barrage_strike_ii", name: "Barrage Strike II", type: "active" },
        { id: "kimberly_energy_boost", name: "Energy Boost", type: "passive" },
        { id: "kimberly_energy_assult_ii", name: "Energy Assult II", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "murphy",
      name: "Murphy",
      rarity: "UR",
      squadType: "tank",
      primaryRole: "tank",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["barrier", "damage_reduction"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "murphy_ironclad_barrier_ii", name: "Ironclad Barrier II", type: "active" },
        { id: "murphy_stand_firm", name: "Stand Firm", type: "passive" },
        { id: "murphy_cannon_fire_ii", name: "Cannon Fire II", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "williams",
      name: "Williams",
      rarity: "UR",
      squadType: "tank",
      primaryRole: "tank",
      secondaryRoles: ["control"],
      damageProfile: "mixed",
      utilityTags: ["stun"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "williams_iron_will", name: "Iron Will", type: "passive" },
        { id: "williams_all_around_armor", name: "All-Around Armor", type: "passive" },
        { id: "williams_stun_bomb", name: "Stun Bomb", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "marshall",
      name: "Marshall",
      rarity: "UR",
      squadType: "tank",
      primaryRole: "buffer",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["command", "team_buff"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "marshall_command_strategy", name: "Command Strategy", type: "passive" },
        { id: "marshall_rapid_start", name: "Rapid Start", type: "passive" },
        { id: "marshall_command_focus_fire", name: "Command: Focus Fire", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "stetmann",
      name: "Stetmann",
      rarity: "UR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: ["control"],
      damageProfile: "aoe",
      utilityTags: ["lightning", "crit"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "stetmann_lightning_rush", name: "Lightning Rush", type: "active" },
        { id: "stetmann_critical_charge", name: "Critical Charge", type: "passive" },
        { id: "stetmann_orb_lightning", name: "Orb Lightning", type: "active" },
      ],
      promotionRules: [],
    },

    // ----------------
    // UR — AIR
    // ----------------
    {
      id: "dva",
      name: "Dva",
      rarity: "UR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: ["buffer"],
      damageProfile: "burst",
      utilityTags: ["precision"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "dva_steel_barrage", name: "Steel Barrage", type: "active" },
        { id: "dva_precision_upgrade", name: "Precision Upgrade", type: "passive" },
        { id: "dva_vertex_missile_ii", name: "Vertex Missile II", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "carlie",
      name: "Carlie",
      rarity: "UR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: ["debuffer"],
      damageProfile: "aoe",
      utilityTags: ["burn", "armor_break"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "carlie_inferno_blaze", name: "Inferno Blaze", type: "active" },
        { id: "carlie_energy_adaption_ii", name: "Energy Adaption II", type: "passive" },
        { id: "carlie_dual_string_rocket", name: "Dual String Rocket", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "morrison",
      name: "Morrison",
      rarity: "UR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "mixed",
      utilityTags: ["armor_piercing"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "morrison_armor_piercing_shot", name: "Armor Piercing Shot", type: "active" },
        { id: "morrison_full_firepower", name: "Full Firepower", type: "passive" },
        { id: "morrison_full_auto_machine_gun", name: "Full Auto Machine Gun", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "lucious",
      name: "Lucious",
      rarity: "UR",
      squadType: "air",
      primaryRole: "tank",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["armor", "mitigation"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "lucious_knights_spirit", name: "Knight's Spirit", type: "passive" },
        { id: "lucious_silver_armor", name: "Silver Armor", type: "passive" },
        { id: "lucious_lightning_triple_strike", name: "Lightning Triple Strike", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "schuyler",
      name: "Schuyler",
      rarity: "UR",
      squadType: "air",
      primaryRole: "control",
      secondaryRoles: ["debuffer"],
      damageProfile: "aoe",
      utilityTags: ["disrupt", "beam"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "schuyler_blast_frenzy", name: "Blast Frenzy", type: "active" },
        { id: "schuyler_antimatter_armor", name: "Antimatter Armor", type: "passive" },
        { id: "schuyler_disruptive_beam", name: "Disruptive Beam", type: "active" },
      ],
      promotionRules: [],
    },

    // ----------------
    // UR — MISSILE
    // ----------------
    {
      id: "tesla",
      name: "Tesla",
      rarity: "UR",
      squadType: "missile",
      primaryRole: "control",
      secondaryRoles: ["damage"],
      damageProfile: "aoe",
      utilityTags: ["lockdown", "chain"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "tesla_electric_grid_lockdown", name: "Electric Grid Lockdown", type: "active" },
        { id: "tesla_electric_power_boost", name: "Electric Power Boost", type: "passive" },
        { id: "tesla_lightning_chain_ii", name: "Lightning Chain II", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "swift",
      name: "Swift",
      rarity: "UR",
      squadType: "missile",
      primaryRole: "damage",
      secondaryRoles: ["debuffer"],
      damageProfile: "singleTarget",
      utilityTags: ["targeting"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "swift_weakness_targeting", name: "Weakness Targeting", type: "passive" },
        { id: "swift_precise_guidance", name: "Precise Guidance", type: "passive" },
        { id: "swift_targeted_strike_ii", name: "Targeted Strike II", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "mcgregor",
      name: "McGregor",
      rarity: "UR",
      squadType: "missile",
      primaryRole: "tank",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["hp_boost", "charge"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "mcgregor_unyielding_heart", name: "Unyielding Heart", type: "passive" },
        { id: "mcgregor_hp_boost", name: "HP Boost", type: "passive" },
        { id: "mcgregor_forward_rush", name: "Forward Rush", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "adam",
      name: "Adam",
      rarity: "UR",
      squadType: "missile",
      primaryRole: "tank",
      secondaryRoles: ["damage"],
      damageProfile: "mixed",
      utilityTags: ["counter", "armor"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "adam_counter_defense", name: "Counter Defense", type: "passive" },
        { id: "adam_spike_armor", name: "Spike Armor", type: "passive" },
        { id: "adam_mk43_vehicle_mounted_machine_gun", name: "Mk43 Vehicle Mounted Machine Gun", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "fiona",
      name: "Fiona",
      rarity: "UR",
      squadType: "missile",
      primaryRole: "damage",
      secondaryRoles: ["buffer"],
      damageProfile: "aoe",
      utilityTags: ["ballistic"],
      inherentTraitIds: ["trait_super_sensing"],
      skills: [
        { id: "fiona_atomic_blast", name: "Atomic Blast", type: "active" },
        { id: "fiona_ballistic_boost", name: "Ballistic Boost", type: "passive" },
        { id: "fiona_double_trajectory", name: "Double Trajectory", type: "active" },
      ],
      promotionRules: [],
    },

    // ----------------
    // SSR — TANK
    // ----------------
    {
      id: "mason",
      name: "Mason",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: ["support"],
      damageProfile: "mixed",
      utilityTags: ["zombie"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "mason_firepower_overload", name: "Firepower Overload", type: "active" },
        { id: "mason_zombie_cleaner", name: "Zombie Cleaner", type: "passive" },
        { id: "mason_rampage_shot", name: "Rampage Shot", type: "active" },
      ],
      promotionRules: [
        {
          toRarity: "UR",
          season: 1,
          permanentIfChosen: true,
          traitReplacesId: "trait_special_tactics",
          traitGainedId: "trait_super_sensing",
          notes: "Upon promotion, Special Tactics becomes UR Super Sensing (per your notes).",
        },
      ],
    },
    {
      id: "violet",
      name: "Violet",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "tank",
      secondaryRoles: ["control"],
      damageProfile: "unknown",
      utilityTags: ["ice", "corrosion"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "violet_chill_corrosion", name: "Chill Corrosion", type: "active" },
        { id: "violet_ice_armor", name: "Ice Armor", type: "passive" },
        { id: "violet_frosty_spray", name: "Frosty Spray", type: "active" },
      ],
      promotionRules: [
        {
          toRarity: "UR",
          season: 2,
          permanentIfChosen: true,
          traitReplacesId: "trait_special_tactics",
          traitGainedId: "trait_super_sensing",
          notes: "Upon promotion, Special Tactics becomes UR Super Sensing (per your notes).",
        },
      ],
    },
    {
      id: "scarlet",
      name: "Scarlet",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "tank",
      secondaryRoles: ["damage"],
      damageProfile: "burst",
      utilityTags: ["fire"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "scarlet_flame_barrier", name: "Flame Barrier", type: "active" },
        { id: "scarlet_armored_shell", name: "Armored Shell", type: "passive" },
        { id: "scarlet_inferno_strike", name: "Inferno Strike", type: "active" },
      ],
      promotionRules: [
        {
          toRarity: "UR",
          season: 3,
          permanentIfChosen: true,
          traitReplacesId: "trait_special_tactics",
          traitGainedId: "trait_super_sensing",
          notes: "Upon promotion, Special Tactics becomes UR Super Sensing (per your notes).",
        },
      ],
    },
    {
      id: "monica",
      name: "Monica",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "support",
      secondaryRoles: ["buffer"],
      damageProfile: "unknown",
      utilityTags: ["scan", "weak_spot", "treasure"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "monica_weak_spot_scan", name: "Weak Spot Scan", type: "passive" },
        { id: "monica_treasure_hunter", name: "Treasure Hunter", type: "passive" },
        { id: "monica_dual_fire_cannon", name: "Dual Fire Cannon", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "farhad",
      name: "Farhad",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "aoe",
      utilityTags: ["missile", "aim"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "farhad_missile_volley", name: "Missile Volley", type: "active" },
        { id: "farhad_precision_aim", name: "Precision Aim", type: "passive" },
        { id: "farhad_missile_strike", name: "Missile Strike", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "richard",
      name: "Richard",
      rarity: "SSR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: ["support"],
      damageProfile: "aoe",
      utilityTags: ["howitzer", "ballistic"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "richard_multi_load", name: "Multi-Load", type: "active" },
        { id: "richard_ballistic_boost", name: "Ballistic Boost", type: "passive" },
        { id: "richard_howitzer", name: "Howitzer", type: "active" },
      ],
      promotionRules: [],
    },

    // ----------------
    // SSR — AIR
    // ----------------
    {
      id: "sarah",
      name: "Sarah",
      rarity: "SSR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: ["support"],
      damageProfile: "mixed",
      utilityTags: ["armor"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "sarah_mg_symphony", name: "MG Symphony", type: "active" },
        { id: "sarah_special_armor", name: "Special Armor", type: "passive" },
        { id: "sarah_gunfire_negotiation", name: "Gunfire Negotiation", type: "active" },
      ],
      promotionRules: [
        {
          toRarity: "UR",
          season: 4,
          permanentIfChosen: true,
          traitReplacesId: "trait_special_tactics",
          traitGainedId: "trait_super_sensing",
          notes: "Gets promoted to UR in S4 if player chooses (per your notes).",
        },
      ],
    },
    {
      id: "cage",
      name: "Cage",
      rarity: "SSR",
      squadType: "air",
      primaryRole: "tank",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["armor", "defense"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "cage_defense_boost", name: "Defense Boost", type: "passive" },
        { id: "cage_z_armor", name: "Z-Armor", type: "passive" },
        { id: "cage_energy_bullet", name: "Energy Bullet", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "maxwell",
      name: "Maxwell",
      rarity: "SSR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "aoe",
      utilityTags: ["zombie", "missile"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "maxwell_destructive_firepower", name: "Destructive Firepower", type: "active" },
        { id: "maxwell_zombie_killer", name: "Zombie Killer", type: "passive" },
        { id: "maxwell_missile_strike", name: "Missile Strike", type: "active" },
      ],
      promotionRules: [],
    },

    // ----------------
    // SSR — MISSILE
    // ----------------
    {
      id: "elsa",
      name: "Elsa",
      rarity: "SSR",
      squadType: "missile",
      primaryRole: "tank",
      secondaryRoles: ["support"],
      damageProfile: "unknown",
      utilityTags: ["armor", "ice"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "elsa_armor_boost", name: "Armor Boost", type: "passive" },
        { id: "elsa_special_armor", name: "Special Armor", type: "passive" },
        { id: "elsa_icicle_strike", name: "Icicle Strike", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "braz",
      name: "Braz",
      rarity: "SSR",
      squadType: "missile",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "aoe",
      utilityTags: ["zombie", "rocket"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "braz_intense_bombing", name: "Intense Bombing", type: "active" },
        { id: "braz_zombie_killer", name: "Zombie Killer", type: "passive" },
        { id: "braz_rocket_spread", name: "Rocket Spread", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "venom",
      name: "Venom",
      rarity: "SSR",
      squadType: "missile",
      primaryRole: "damage",
      secondaryRoles: ["buffer"],
      damageProfile: "burst",
      utilityTags: ["energy"],
      inherentTraitIds: ["trait_special_tactics"],
      skills: [
        { id: "venom_energy_overload", name: "Energy Overload", type: "active" },
        { id: "venom_core_surge", name: "Core Surge", type: "passive" },
        { id: "venom_energy_bullet", name: "Energy Bullet", type: "active" },
      ],
      promotionRules: [
        {
          toRarity: "UR",
          season: 5,
          permanentIfChosen: true,
          traitReplacesId: "trait_special_tactics",
          traitGainedId: "trait_super_sensing",
          notes: "Gets promoted to UR in S5 if player chooses (per your notes).",
        },
      ],
    },

    // ----------------
    // SR
    // ----------------
    {
      id: "gump",
      name: "Gump",
      rarity: "SR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "burst",
      utilityTags: ["fire"],
      inherentTraitIds: ["trait_field_combat"],
      skills: [
        { id: "gump_flame_boost", name: "Flame Boost", type: "passive" },
        { id: "gump_flame_burst", name: "Flame Burst", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "loki",
      name: "Loki",
      rarity: "SR",
      squadType: "tank",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "burst",
      utilityTags: ["shotgun"],
      inherentTraitIds: ["trait_field_combat"],
      skills: [
        { id: "loki_grapeshot_burst", name: "Grapeshot Burst", type: "active" },
        { id: "loki_shotgun", name: "Shotgun", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "ambolt",
      name: "Ambolt",
      rarity: "SR",
      squadType: "air",
      primaryRole: "damage",
      secondaryRoles: [],
      damageProfile: "aoe",
      utilityTags: ["missile"],
      inherentTraitIds: ["trait_field_combat"],
      skills: [
        { id: "ambolt_missile_barrage", name: "Missile Barrage", type: "active" },
        { id: "ambolt_missile_strikes", name: "Missile Strikes", type: "active" },
      ],
      promotionRules: [],
    },
    {
      id: "kane",
      name: "Kane",
      rarity: "SR",
      squadType: "missile",
      primaryRole: "damage",
      secondaryRoles: ["control"],
      damageProfile: "aoe",
      utilityTags: ["grenade"],
      inherentTraitIds: ["trait_field_combat"],
      skills: [
        { id: "kane_grenade_barrage", name: "Grenade Barrage", type: "active" },
        { id: "kane_blasting_grenade", name: "Blasting Grenade", type: "active" },
      ],
      promotionRules: [],
    },
  ],
};

export const HERO_CATALOG = HeroCatalogSchema.parse(CATALOG);

// Convenience exports
export const HEROES = HERO_CATALOG.heroes;
export const TRAITS = HERO_CATALOG.traits;

